name: Publish To GitHub Actions

on:
  push:
    branches: [dev]

jobs:
  build-services:
    name: Build Services
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish Angular App
        run: npm run build
      
      # - name: rename base-tag to work with GitHub Pages
      #   run: sed -i 's/<base href="\/" \/>/<base href="\/anngel\/" \/>/g' release/wwwroot/index.html
      
      - name: copy 404
        run: cp dist/index.html dist/404.html
      
      - name: Add .nojekyll
        run: touch dist/.nojekyll
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token	: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist